# Generated by Django 2.1.7 on 2019-03-15 14:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('postID', models.CharField(help_text='Unique ID for this post', max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('expiry', models.DateField(default=datetime.date.today)),
                ('private', models.BooleanField(default=0)),
                ('pasteContent', models.CharField(max_length=2000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postshares', models.ManyToManyField(blank=True, related_name='postshares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
