# Generated by Django 2.1.7 on 2019-03-05 02:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('postID', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this post', primary_key=True, serialize=False)),
                ('expiry', models.DateField(default=datetime.date.today)),
                ('private', models.BooleanField(default=0)),
                ('pasteContent', models.CharField(max_length=2000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
