# Generated by Django 2.1.7 on 2019-03-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostessPasties', '0002_auto_20190312_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttable',
            name='postID',
            field=models.CharField(default='ba6a7tke', help_text='Unique ID for this post', max_length=8, primary_key=True, serialize=False),
        ),
    ]
