# Generated by Django 2.1.7 on 2019-03-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostessPasties', '0004_auto_20190312_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttable',
            name='postID',
            field=models.CharField(default='2fuvpm5r', help_text='Unique ID for this post', max_length=8, primary_key=True, serialize=False),
        ),
    ]
