# Generated by Django 2.1.7 on 2019-03-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HostessPasties', '0011_auto_20190314_1237'),
        ('HostessPasties', '0011_auto_20190314_1311'),
    ]

    operations = [
    ]
