# Generated by Django 2.1.7 on 2019-03-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostessPasties', '0017_auto_20190314_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttable',
            name='postID',
            field=models.CharField(default='4ouegzdx', help_text='Unique ID for this post', max_length=8, primary_key=True, serialize=False),
        ),
    ]
