# Generated by Django 2.1.7 on 2019-03-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostessPasties', '0020_auto_20190314_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttable',
            name='postID',
            field=models.CharField(default='onxa3cgs', help_text='Unique ID for this post', max_length=8, primary_key=True, serialize=False),
        ),
    ]
