# Generated by Django 2.1.7 on 2019-03-15 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HostessPasties', '0020_auto_20190314_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttable',
            name='postshares',
            field=models.ManyToManyField(blank=True, related_name='postshares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posttable',
            name='postID',
            field=models.CharField(default='1112wn7s', help_text='Unique ID for this post', max_length=8, primary_key=True, serialize=False),
        ),
    ]
