# Generated by Django 2.1.7 on 2019-03-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostessPasties', '0023_auto_20190314_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttable',
            name='postID',
            field=models.CharField(default='jug1n8f1', help_text='Unique ID for this post', max_length=8, primary_key=True, serialize=False),
        ),
    ]
