from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import PostTable
import datetime
class AccountCreation(UserCreationForm):
        #fields for user account creation
        username = forms.CharField(max_length=32)
        email = forms.EmailField(max_length=254, help_text='Required. Input a valid email address.')
        first_name = forms.CharField(max_length=50)
        last_name = forms.CharField(max_length=50)
        #use user model with specific fields for form
        class Meta:
            model = User
            fields = ('username','email','first_name','last_name')

class PostCreation(forms.ModelForm):
    #fields for post account creation these fields the user is going to input. The rest are
    #generated by django or through other means
    pasteContent = forms.CharField(widget=forms.Textarea)
    expiry = forms.DateField(widget=forms.SelectDateWidget)
    #use posttable model with specific fields for form 
    class Meta:
        model = PostTable
        fields = ('title','expiry','private','pasteContent','postshares')
